//! Message model
//!
//! A message represents a single turn in a conversation between a user
//! and the AI assistant. Messages can originate from users (via text,
//! voice, or screen interaction) or from the AI assistant.
//!
//! # Message Structure
//!
//! Each message contains:
//! - Unique ID (UUID v7 for time-ordering)
//! - Role (user, assistant, or system)
//! - Content (the actual message text)
//! - Timestamp (RFC3339)
//! - Metadata (input mode, confidence, model used, processing time)
//!
//! # Input Modes
//!
//! - **Text**: Typed input from keyboard
//! - **Voice**: Speech-to-text via Vosk STT
//! - **Screen**: Screen interaction captured via computer vision

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Role of the message sender
///
/// Determines how the message is displayed and processed.
/// - User messages appear on the left (or right based on platform)
/// - Assistant messages contain AI responses
/// - System messages are internal instructions
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// User message - from the human user
    User,
    /// AI assistant response - generated by the AI
    Assistant,
    /// System prompt or instruction - internal to TERMIO
    System,
}

/// Input mode for the message
///
/// Records how the message was originally created,
/// useful for analytics and improving user experience.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum InputMode {
    /// Typed text input from keyboard
    Text,
    /// Voice input (Speech-to-Text via Vosk)
    Voice,
    /// Screen interaction captured via computer vision
    Screen,
}

/// Metadata for a message
///
/// Additional information about how the message was created
/// and processed. Useful for debugging and analytics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageMetadata {
    /// How the message was input (text, voice, screen)
    pub input_mode: InputMode,

    /// Confidence score (0-1) for voice/screen input
    /// None for typed text, Some for speech recognition
    pub confidence: Option<f32>,

    /// Which model was used for AI responses
    /// e.g., "llama-3-8b", "gpt-4o", "claude-3.5-sonnet"
    pub model_used: Option<String>,

    /// Processing time in milliseconds
    /// How long it took to generate the response
    pub processing_time_ms: Option<u64>,
}

impl Default for MessageMetadata {
    fn default() -> Self {
        Self {
            input_mode: InputMode::Text,
            confidence: None,
            model_used: None,
            processing_time_ms: None,
        }
    }
}

/// A single message in a conversation
///
/// The fundamental unit of communication in TERMIO.
/// Messages are immutable once created - to modify, create a new one.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Unique message ID (UUID v7 for time-ordering)
    /// UUID v7 embeds timestamp in the ID
    pub id: Uuid,

    /// Message role (user, assistant, or system)
    pub role: Role,

    /// Message content - the actual text
    pub content: String,

    /// When the message was created
    pub timestamp: DateTime<Utc>,

    /// Additional metadata about the message
    pub metadata: MessageMetadata,
}

impl Message {
    /// Create a new user message
    ///
    /// Convenience constructor for user-originated messages.
    /// Sets role to User and timestamp to now.
    ///
    /// # Arguments
    ///
    /// * `content` - The message text
    ///
    /// # Returns
    ///
    /// A new Message with role=User
    ///
    /// # Example
    ///
    /// ```rust
    /// use termio_core::models::Message;
    ///
    /// let msg = Message::user("Hello, TERMIO!");
    /// assert!(msg.role == Role::User);
    /// ```
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            id: Uuid::now_v7(),
            role: Role::User,
            content: content.into(),
            timestamp: Utc::now(),
            metadata: MessageMetadata::default(),
        }
    }

    /// Create a new assistant message
    ///
    /// Convenience constructor for AI-generated responses.
    /// Sets role to Assistant and timestamp to now.
    ///
    /// # Arguments
    ///
    /// * `content` - The AI's response text
    ///
    /// # Returns
    ///
    /// A new Message with role=Assistant
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            id: Uuid::now_v7(),
            role: Role::Assistant,
            content: content.into(),
            timestamp: Utc::now(),
            metadata: MessageMetadata::default(),
        }
    }

    /// Create a new system message
    ///
    /// For internal system instructions and prompts.
    /// Not typically used for user-visible content.
    ///
    /// # Arguments
    ///
    /// * `content` - The system instruction
    ///
    /// # Returns
    ///
    /// A new Message with role=System
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            id: Uuid::now_v7(),
            role: Role::System,
            content: content.into(),
            timestamp: Utc::now(),
            metadata: MessageMetadata::default(),
        }
    }

    /// Set the model used for this message
    ///
    /// Builder pattern for setting the AI model.
    /// Use after creating an assistant message.
    ///
    /// # Arguments
    ///
    /// * `model` - Model identifier string
    ///
    /// # Returns
    ///
    /// Message with model_used set
    ///
    /// # Example
    ///
    /// ```rust
    /// use termio_core::models::Message;
    ///
    /// let msg = Message::assistant("Hello!")
    ///     .with_model("llama-3-8b")
    ///     .with_processing_time(150);
    /// ```
    pub fn with_model(mut self, model: impl Into<String>) -> Self {
        self.metadata.model_used = Some(model.into());
        self
    }

    /// Set the processing time
    ///
    /// Records how long the AI took to generate this response.
    ///
    /// # Arguments
    ///
    /// * `ms` - Processing time in milliseconds
    ///
    /// # Returns
    ///
    /// Message with processing_time_ms set
    pub fn with_processing_time(mut self, ms: u64) -> Self {
        self.metadata.processing_time_ms = Some(ms);
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_message_creation() {
        let msg = Message::user("Hello, world!");
        assert_eq!(msg.role, Role::User);
        assert_eq!(msg.content, "Hello, world!");
    }

    #[test]
    fn test_message_with_metadata() {
        let msg = Message::assistant("Hi there!")
            .with_model("llama-7b")
            .with_processing_time(150);

        assert_eq!(msg.metadata.model_used, Some("llama-7b".to_string()));
        assert_eq!(msg.metadata.processing_time_ms, Some(150));
    }
}
